export enum actionConstants {
  GetSelectedProduct = "GetSelectedProduct",
  SELECTED_PRODUCT = "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT",

  ADD_TO_CART = "ADD_TO_CART",
  ADD_TO_CART_FROM_PRODUCT_PAGE = "ADD_TO_CART_FROM_PRODUCT_PAGE",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  ADJUST_QTY = "ADJUST_QTY",
  LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM",

  SAVE_IN_LOCAL_STORAGE = "SAVE_IN_LOCAL_STORAGE",
  TAKE_FROM_LOCAL_STORAGE = "TAKE_FROM_LOCAL_STORAGE",
  GET_SEARCH_PRODUCT = "GET_SEARCH_PRODUCT",

  CLEAR_LOCAL_STORAGE = "CLEAR_LOCAL_STORAGE",

  REMOVE_ALL_PRODUCTS_FROM_CART = "REMOVE_ALL_PRODUCTS_FROM_CART  ",
}
